server:
    port: 8761
spring:
  application:
    name: spring_eureka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
management:
    endpoints:
        web:
        exposure:
            include: "*"
